### ISSUE TITLE
Some Legendaries missing when applying filter

### ISSUE THREAD

**Issue by Linkk93** [th3conc3pt3ur/torchlight-helper#1]
Hi and thanks for this great page!

I noticed that some legendaries are missing when I apply an item filter. For example:

When I select Helmet > INT Helmet I am missing two items: 
 - Surging Inspiration
 - Cold Breath

For DEX Helmet I am missing: 
 - Blind Vision

But both items are in the complete legendary list or only apply the Helmet filter, so I guess some tag is missing or wrong for the filter.

I tried that in different browsers and in incognito mode, so I don't think this is a cache issue.

**Comment by th3conc3pt3ur** [comment]
Thx for your report, we will look at that

**Comment by th3conc3pt3ur** [comment]
Should be fixed now @Linkk93 can you confirm ?

**Comment by Linkk93** [comment]
Yes, I can confirm the fix.

Thank you!
